// ======= DO NOT EDIT THIS FILE ============
public class Dog
 {String owner;
  int color,price;
  Dog(String xOwner, int xColor, int xPrice)
   {owner=xOwner;color=xColor;price=xPrice;
   }
  public String toString()
   {return("(" + owner + "," + color + "," + price + ")");
   }
 }
