/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.lab221.P0011.GUI;

import javax.swing.*;
import com.fpt.lab221.P0011.OB.Calculator;

/**
 *
 * @author lab003
 */
public class SimpleCalculator extends javax.swing.JFrame {

//    Calculator calcu = new Calculator();
    int operator = -1;
    double firstNum = 0;
    double secondNum = 0;
    boolean calcu = false;
    boolean calcuM = false;

    /**
     * Creates new form SimpleCalculator
     */
    public SimpleCalculator() {
        initComponents();
        setTitle("Simple Calculator");
    }

    public void result() {
        float convertNumber = Float.parseFloat("" + firstNum);
        jTextFieldDisplay.setText(convertNumber + "");
    }

    public void cal() throws Exception {
        if (!calcu) {
            if (operator == -1) {
                firstNum = getValue();
            } else {
                secondNum = getValue();
                if (operator == 1) {
                    firstNum += secondNum;
                    result();
                }
                if (operator == 2) {
                    firstNum -= secondNum;
                    result();
                }
                if (operator == 3) {
                    firstNum *= secondNum;
                    result();
                }
                if (operator == 4) {
                    if (secondNum == 0) {
                        jTextFieldDisplay.setText("Error");
                        jButtonNumber0.setEnabled(false);
                        jButtonNumber1.setEnabled(false);
                        jButtonNumber2.setEnabled(false);
                        jButtonNumber3.setEnabled(false);
                        jButtonNumber4.setEnabled(false);
                        jButtonNumber5.setEnabled(false);
                        jButtonNumber6.setEnabled(false);
                        jButtonNumber7.setEnabled(false);
                        jButtonNumber8.setEnabled(false);
                        jButtonNumber9.setEnabled(false);
                        jButtonOperatorPlus.setEnabled(false);
                        jButtonOperatorMini.setEnabled(false);
                        jButtonOperatorMul.setEnabled(false);
                        jButtonOperatorDivide.setEnabled(false);
                        jButtonOperatorEqual.setEnabled(false);
                    } else {
                        firstNum /= secondNum;
                        result();
                    }
                }
            }
            calcu = true;
        }
    }

    public float getValue() {
        String value = jTextFieldDisplay.getText();
        if (value.endsWith(".")) {
            value = value.replace(".", "");
        }
        return Float.parseFloat(value);
    }

    public void pressNumber(String value) {
        if (calcu || calcuM) {
            jTextFieldDisplay.setText("0");
            calcu = false;
            calcuM = false;
        }
        if (jTextFieldDisplay.getText().equals("0")) {
            jTextFieldDisplay.setText(value);
        } else {
            jTextFieldDisplay.setText(jTextFieldDisplay.getText() + value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNumber7 = new javax.swing.JButton();
        jButtonNumber8 = new javax.swing.JButton();
        jButtonNumber9 = new javax.swing.JButton();
        jButtonOperatorPlus = new javax.swing.JButton();
        jButtonNumber4 = new javax.swing.JButton();
        jButtonNumber5 = new javax.swing.JButton();
        jButtonNumber6 = new javax.swing.JButton();
        jButtonOperatorMini = new javax.swing.JButton();
        jButtonNumber2 = new javax.swing.JButton();
        jButtonNumber3 = new javax.swing.JButton();
        jButtonOperatorDivide = new javax.swing.JButton();
        jButtonNumber0 = new javax.swing.JButton();
        jButtonOperatorMul = new javax.swing.JButton();
        jButtonNumber1 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonOperatorEqual = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonNumber7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber7.setText("7");
        jButtonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber7ActionPerformed(evt);
            }
        });

        jButtonNumber8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber8.setText("8");
        jButtonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber8ActionPerformed(evt);
            }
        });

        jButtonNumber9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber9.setText("9");
        jButtonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber9ActionPerformed(evt);
            }
        });

        jButtonOperatorPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperatorPlus.setText("+");
        jButtonOperatorPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperatorPlusActionPerformed(evt);
            }
        });

        jButtonNumber4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber4.setText("4");
        jButtonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber4ActionPerformed(evt);
            }
        });

        jButtonNumber5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber5.setText("5");
        jButtonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber5ActionPerformed(evt);
            }
        });

        jButtonNumber6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber6.setText("6");
        jButtonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber6ActionPerformed(evt);
            }
        });

        jButtonOperatorMini.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperatorMini.setText("-");
        jButtonOperatorMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperatorMiniActionPerformed(evt);
            }
        });

        jButtonNumber2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber2.setText("2");
        jButtonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber2ActionPerformed(evt);
            }
        });

        jButtonNumber3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber3.setText("3");
        jButtonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber3ActionPerformed(evt);
            }
        });

        jButtonOperatorDivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperatorDivide.setText("/");
        jButtonOperatorDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperatorDivideActionPerformed(evt);
            }
        });

        jButtonNumber0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber0.setText("0");
        jButtonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber0ActionPerformed(evt);
            }
        });

        jButtonOperatorMul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperatorMul.setText("*");
        jButtonOperatorMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperatorMulActionPerformed(evt);
            }
        });

        jButtonNumber1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNumber1.setText("1");
        jButtonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber1ActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonOperatorEqual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOperatorEqual.setText("=");
        jButtonOperatorEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperatorEqualActionPerformed(evt);
            }
        });

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButtonOperatorPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOperatorMini, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOperatorDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOperatorMul, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOperatorEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOperatorPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNumber9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNumber4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOperatorMini, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNumber6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOperatorMul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOperatorDivide, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButtonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOperatorEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber1ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("1");
        pressNumber("1");
    }//GEN-LAST:event_jButtonNumber1ActionPerformed

    private void jButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber2ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("2");
        pressNumber("2");
    }//GEN-LAST:event_jButtonNumber2ActionPerformed

    private void jButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber3ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("3");
        pressNumber("3");
    }//GEN-LAST:event_jButtonNumber3ActionPerformed

    private void jButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber4ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("4");
        pressNumber("4");
    }//GEN-LAST:event_jButtonNumber4ActionPerformed

    private void jButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber5ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("5");
        pressNumber("5");
    }//GEN-LAST:event_jButtonNumber5ActionPerformed

    private void jButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber6ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("6");
        pressNumber("6");
    }//GEN-LAST:event_jButtonNumber6ActionPerformed

    private void jButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber7ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("7");
        pressNumber("7");
    }//GEN-LAST:event_jButtonNumber7ActionPerformed

    private void jButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber8ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("8");
        pressNumber("8");
    }//GEN-LAST:event_jButtonNumber8ActionPerformed

    private void jButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber9ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("9");
        pressNumber("9");
    }//GEN-LAST:event_jButtonNumber9ActionPerformed

    private void jButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber0ActionPerformed
        // TODO add your handling code here:
//        calcu.pressNumber("0");
        pressNumber("0");
    }//GEN-LAST:event_jButtonNumber0ActionPerformed

    private void jButtonOperatorPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperatorPlusActionPerformed
        // TODO add your handling code here:
        try {
//            calcu.cal();
            cal();
        } catch (Exception e) {
            jTextFieldDisplay.setText("MathError");
        }
        operator = 1;
    }//GEN-LAST:event_jButtonOperatorPlusActionPerformed

    private void jButtonOperatorMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperatorMiniActionPerformed
        // TODO add your handling code here:
        try {
//            calcu.cal();
            cal();
        } catch (Exception e) {
            jTextFieldDisplay.setText("MathError");
        }
        operator = 2;
    }//GEN-LAST:event_jButtonOperatorMiniActionPerformed

    private void jButtonOperatorMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperatorMulActionPerformed
        // TODO add your handling code here:
        try {
//            calcu.cal();
            cal();
        } catch (Exception e) {
            jTextFieldDisplay.setText("MathError");
        }
        operator = 3;
    }//GEN-LAST:event_jButtonOperatorMulActionPerformed

    private void jButtonOperatorDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperatorDivideActionPerformed
        // TODO add your handling code here:
        try {
//            calcu.cal();
            cal();
        } catch (Exception e) {
            jTextFieldDisplay.setText("MathError");
        }
        operator = 4;
    }//GEN-LAST:event_jButtonOperatorDivideActionPerformed

    private void jButtonOperatorEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperatorEqualActionPerformed
        // TODO add your handling code here:
        try {
//            calcu.cal();
            cal();
        } catch (Exception e) {
            jTextFieldDisplay.setText("MathError");
        }
        operator = -1;
    }//GEN-LAST:event_jButtonOperatorEqualActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jButtonNumber0.setEnabled(true);
        jButtonNumber1.setEnabled(true);
        jButtonNumber2.setEnabled(true);
        jButtonNumber3.setEnabled(true);
        jButtonNumber4.setEnabled(true);
        jButtonNumber5.setEnabled(true);
        jButtonNumber6.setEnabled(true);
        jButtonNumber7.setEnabled(true);
        jButtonNumber8.setEnabled(true);
        jButtonNumber9.setEnabled(true);
        jButtonOperatorPlus.setEnabled(true);
        jButtonOperatorMini.setEnabled(true);
        jButtonOperatorMul.setEnabled(true);
        jButtonOperatorDivide.setEnabled(true);
        jButtonOperatorEqual.setEnabled(true);
        jTextFieldDisplay.setText("0");
        operator = -1;
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonNumber0;
    private javax.swing.JButton jButtonNumber1;
    private javax.swing.JButton jButtonNumber2;
    private javax.swing.JButton jButtonNumber3;
    private javax.swing.JButton jButtonNumber4;
    private javax.swing.JButton jButtonNumber5;
    private javax.swing.JButton jButtonNumber6;
    private javax.swing.JButton jButtonNumber7;
    private javax.swing.JButton jButtonNumber8;
    private javax.swing.JButton jButtonNumber9;
    private javax.swing.JButton jButtonOperatorDivide;
    private javax.swing.JButton jButtonOperatorEqual;
    private javax.swing.JButton jButtonOperatorMini;
    private javax.swing.JButton jButtonOperatorMul;
    private javax.swing.JButton jButtonOperatorPlus;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
