// ======= DO NOT EDIT THIS FILE ============

public class Box {

    String color;
    int area, peri;

    Box(String xColor, int xArea, int xPeri) {
        color = xColor;
        area = xArea;
        peri = xPeri;
    }

    public String toString() {
        return ("(" + color + "," + area + "," + peri + ")");
    }
}
