// ======= DO NOT EDIT THIS FILE ============

public class Node {

    Box info;
    Node left, right;
    int bal, level;

    Node(Box x) {
        info = x;
        left = right = null;
    }
}
