// ======= DO NOT EDIT THIS FILE ============
import java.util.*;
public class GQueue
  {LinkedList<Integer> t;
   GQueue() {t=new LinkedList<Integer>();}
   boolean isEmpty() {return(t.isEmpty());}
   void clear() {t.clear();}
   void enqueue(int x) {t.addLast(x);}
   Integer dequeue() 
     {if(isEmpty()) return(null);
      return(t.removeFirst());
     }
   Integer front() 
     {if(isEmpty()) return(null);
      return(t.getFirst());
     }
  }

