/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

// ======= DO NOT EDIT THIS FILE ============
class Node {
   Boo info;
   Node left,right;
   int bal,level;
   Node(){
     }  
   Node(Boo x) {
    info=x;left=right=null;
     }  
   }

