/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

// ======= DO NOT EDIT THIS FILE ===============
//This queue is used for BSTree breadth-first traversal
//-------------------------------------------------------------------------
import java.util.*;
public class Queue {
  LinkedList<Node> t;
  Queue() {
    t=new LinkedList<Node>();
    }
   boolean isEmpty() {
     return(t.isEmpty());
    }
   void enqueue(Node p) {
     t.addLast(p);
    }
   Node dequeue() { 
     if(isEmpty()) return(null);
     return(t.removeFirst());
    }
   Node front() { 
     if(isEmpty()) return(null);
     return(t.getFirst());
    }
  }

