// ======= DO NOT EDIT THIS FILE ============
class Ball {
  String maker;
  int type,radius;
  Ball() {
   }
  Ball(String xMaker, int xType, int xRadius){
    maker=xMaker;type=xType; radius=xRadius;
   }
  public String toString(){
    return("(" +maker+","+type + "," + radius + ")");
   }
 }
