// ======= DO NOT EDIT THIS FILE ============
class Person
 {String name;
  int age;
  Person(String xName, int xAge)
   {name=xName; age = xAge;
   }
  public String toString() //Do not edit the toString() function, because it is used to display required output
   {return("(" +name+","+ age + ")");
   }
 }
