// ======= DO NOT EDIT THIS FILE ============
class Node {
  Ball info;
  Node next;
  Node() {
   }
  Node(Ball x, Node p) {
    info=x;next=p;
   }
  Node(Ball x) {
    this(x,null);
   }
 }

