/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.lab221.P0001.GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author lab026
 */
public class DisplayAndResizeImageFrame extends javax.swing.JFrame {

    ImageIcon icon1 = new ImageIcon("Images/1.jpg");
    ImageIcon icon2 = new ImageIcon("Images/2.jpg");
    ImageIcon icon3 = new ImageIcon("Images/3.jpg");
    ImageIcon icon4 = new ImageIcon("Images/4.jpg");
    ImageIcon icon5 = new ImageIcon("Images/5.jpg");

    /**
     * Creates new form DisplayAndResizeImageFrame
     */
    public DisplayAndResizeImageFrame() {
        initComponents();
        setImagesforButton(jButtonImage1, icon1);
        setImagesforButton(jButtonImage2, icon2);
        setImagesforButton(jButtonImage3, icon3);
        setImagesforButton(jButtonImage4, icon4);
        setImagesforButton(jButtonImage5, icon5);
    }

    private void setImagesforButton(JButton jb, ImageIcon ic) {
        /*
            This fuction set a image for a button.
         */
        Image im = ic.getImage().getScaledInstance(jb.getWidth() - 10,
                jb.getHeight() - 10, java.awt.Image.SCALE_SMOOTH);
        jb.setIcon(new ImageIcon(im));
    }

    private void setImagesforLabel(JLabel jl, ImageIcon ic) {
        /*
            This fuction set a image for a label.
         */
        Image im = ic.getImage().getScaledInstance(jl.getWidth(),
                jl.getHeight(), java.awt.Image.SCALE_SMOOTH);
        jl.setIcon(new ImageIcon(im));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jToolBarButton = new javax.swing.JToolBar();
        jPanelButton = new javax.swing.JPanel();
        jButtonImage1 = new javax.swing.JButton();
        jButtonImage3 = new javax.swing.JButton();
        jButtonImage2 = new javax.swing.JButton();
        jButtonImage5 = new javax.swing.JButton();
        jButtonImage4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBarButton.setRollover(true);

        jButtonImage1.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage1ActionPerformed(evt);
            }
        });

        jButtonImage3.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonImage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage3ActionPerformed(evt);
            }
        });

        jButtonImage2.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage2ActionPerformed(evt);
            }
        });

        jButtonImage5.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonImage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage5ActionPerformed(evt);
            }
        });

        jButtonImage4.setPreferredSize(new java.awt.Dimension(75, 75));
        jButtonImage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButtonImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonImage4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jButtonImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBarButton.add(jPanelButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage1ActionPerformed
        // TODO add your handling code here:
        setImagesforLabel(jLabelImage, icon1);
    }//GEN-LAST:event_jButtonImage1ActionPerformed

    private void jButtonImage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage3ActionPerformed
        // TODO add your handling code here:
        setImagesforLabel(jLabelImage, icon3);
    }//GEN-LAST:event_jButtonImage3ActionPerformed

    private void jButtonImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage2ActionPerformed
        // TODO add your handling code here:
        setImagesforLabel(jLabelImage, icon2);
    }//GEN-LAST:event_jButtonImage2ActionPerformed

    private void jButtonImage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage5ActionPerformed
        // TODO add your handling code here:
        setImagesforLabel(jLabelImage, icon5);
    }//GEN-LAST:event_jButtonImage5ActionPerformed

    private void jButtonImage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage4ActionPerformed
        // TODO add your handling code here:
        setImagesforLabel(jLabelImage, icon4);
    }//GEN-LAST:event_jButtonImage4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayAndResizeImageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImage1;
    private javax.swing.JButton jButtonImage2;
    private javax.swing.JButton jButtonImage3;
    private javax.swing.JButton jButtonImage4;
    private javax.swing.JButton jButtonImage5;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JToolBar jToolBarButton;
    // End of variables declaration//GEN-END:variables
}
