/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.lab221.P0010.GUI;

import java.awt.Color;

/**
 *
 * @author lab030
 */
public class BackgroundFrame extends javax.swing.JFrame {

    /**
     * Creates new form BackgroundFrame
     */
    public BackgroundFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonRed = new javax.swing.JButton();
        jButtonGreen = new javax.swing.JButton();
        jButtonBlue = new javax.swing.JButton();
        jToggleButtonX = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText.setEditable(false);
        jText.setColumns(20);
        jText.setRows(5);
        jScrollPane1.setViewportView(jText);

        jToolBar1.setRollover(true);

        jButtonRed.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fpt/lab221/P0010/GUI/Red.PNG"))); // NOI18N
        jButtonRed.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonRed.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonRed.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRed);

        jButtonGreen.setBackground(new java.awt.Color(102, 255, 51));
        jButtonGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fpt/lab221/P0010/GUI/Green.PNG"))); // NOI18N
        jButtonGreen.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonGreen.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonGreen.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGreenActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGreen);

        jButtonBlue.setBackground(new java.awt.Color(0, 0, 204));
        jButtonBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fpt/lab221/P0010/GUI/Blue.PNG"))); // NOI18N
        jButtonBlue.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonBlue.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonBlue.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlueActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonBlue);

        jToggleButtonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fpt/lab221/P0010/GUI/Capture.PNG"))); // NOI18N
        jToggleButtonX.setMaximumSize(new java.awt.Dimension(100, 100));
        jToggleButtonX.setMinimumSize(new java.awt.Dimension(100, 100));
        jToggleButtonX.setPreferredSize(new java.awt.Dimension(100, 100));
        jToggleButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonXActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonX);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlueActionPerformed
        // TODO add your handling code here:
        jText.setBackground(Color.BLUE);
    }//GEN-LAST:event_jButtonBlueActionPerformed

    private void jButtonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedActionPerformed
        // TODO add your handling code here:
        jText.setBackground(Color.RED);
    }//GEN-LAST:event_jButtonRedActionPerformed

    private void jButtonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreenActionPerformed
        // TODO add your handling code here:
        jText.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonGreenActionPerformed

    private void jToggleButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonXActionPerformed
        // TODO add your handling code here:
        jText.setBackground(Color.WHITE);
    }//GEN-LAST:event_jToggleButtonXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackgroundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackgroundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackgroundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackgroundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackgroundFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBlue;
    private javax.swing.JButton jButtonGreen;
    private javax.swing.JButton jButtonRed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jText;
    private javax.swing.JToggleButton jToggleButtonX;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
