// ======= DO NOT EDIT THIS FILE ============
class Node {
   Corn info;
   Node left,right;
   int bal,level;
   Node(){
     }  
   Node(Corn x) {
    info=x;left=right=null;
     }  
   }
