package com.fpt.lab221.P0111.GUI;

import com.fpt.lab221.P0111.OB.LogicCalculator;
import java.math.BigDecimal;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lab003
 */
public class Calculator extends javax.swing.JFrame {

    LogicCalculator logic = new LogicCalculator();
    double firstNum = 0;
    double secondNum = 0;
    double total = 0;
    double memory = 0;
    boolean zeroDisp = false;
    boolean decDisp = false;
    boolean numberAdd = false;
    boolean acPress = true;
    int operator = 0;

    /**
     * Creates new form Main
     */
    public Calculator() {
        initComponents();
    }

    public void addText(JButton btn) {
        if (acPress) {
            if (!zeroDisp && !decDisp) {
                jTextFieldDisplay.setText(null);
            }
            jTextFieldDisplay.setText(jTextFieldDisplay.getText() + btn.getText());
            zeroDisp = true;
            numberAdd = true;
        }
    }

    public void setText() {
        if (total > -100000000 && total < 1000000000) {
            BigDecimal bigDec = BigDecimal.valueOf(total);

            jTextFieldDisplay.setText(String.valueOf(bigDec.doubleValue()));
        } else {
            jTextFieldDisplay.setText("Math Error");
        }
    }

    public void prevTotal() {
        if (acPress) {
            if (operator == 0) {
                try {
                    firstNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                } catch (Exception e) {
                    jTextFieldDisplay.setText("Syntax Error");
                    acPress = false;
                }
            } else {
                try {
                    secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                } catch (Exception e) {
                    jTextFieldDisplay.setText("Syntax Error");
                    acPress = false;
                }
            }
            if (numberAdd) {
                if (operator == 1) {
                    firstNum = logic.add(firstNum, secondNum);
                } else if (operator == 2) {
                    firstNum = logic.substract(firstNum, secondNum);
                } else if (operator == 3) {
                    firstNum = logic.multiply(firstNum, secondNum);
                } else if (operator == 4) {
                    firstNum = logic.divide(firstNum, secondNum);
                }
            }
            jTextFieldDisplay.setText(String.valueOf(firstNum));
            zeroDisp = false;
            decDisp = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unzeroDisped")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNumber1 = new javax.swing.JButton();
        jButtonNumber2 = new javax.swing.JButton();
        jButtonNumber3 = new javax.swing.JButton();
        jButtonNumber4 = new javax.swing.JButton();
        jButtonNumber5 = new javax.swing.JButton();
        jButtonNumber6 = new javax.swing.JButton();
        jButtonNumber7 = new javax.swing.JButton();
        jButtonNumber8 = new javax.swing.JButton();
        jButtonNumber9 = new javax.swing.JButton();
        jButtonNumber0 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButtonMul = new javax.swing.JButton();
        jButtonDivi = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonDecimal = new javax.swing.JButton();
        jButtonNegative = new javax.swing.JButton();
        jButtonDividedByX = new javax.swing.JButton();
        jButtonPercent = new javax.swing.JButton();
        jButtonSqrtRoot = new javax.swing.JButton();
        jButtonBackspace = new javax.swing.JButton();
        jButtonMemoryClear = new javax.swing.JButton();
        jButtonMemoryRead = new javax.swing.JButton();
        jButtonMemorySave = new javax.swing.JButton();
        jButtonMemoryAdd = new javax.swing.JButton();
        jButtonMemorySub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        jButtonNumber1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber1.setText("1");
        jButtonNumber1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber1ActionPerformed(evt);
            }
        });

        jButtonNumber2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber2.setText("2");
        jButtonNumber2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber2ActionPerformed(evt);
            }
        });

        jButtonNumber3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber3.setText("3");
        jButtonNumber3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber3ActionPerformed(evt);
            }
        });

        jButtonNumber4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber4.setText("4");
        jButtonNumber4.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber4ActionPerformed(evt);
            }
        });

        jButtonNumber5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber5.setText("5");
        jButtonNumber5.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber5ActionPerformed(evt);
            }
        });

        jButtonNumber6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber6.setText("6");
        jButtonNumber6.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber6ActionPerformed(evt);
            }
        });

        jButtonNumber7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber7.setText("7");
        jButtonNumber7.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber7ActionPerformed(evt);
            }
        });

        jButtonNumber8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber8.setText("8");
        jButtonNumber8.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber8ActionPerformed(evt);
            }
        });

        jButtonNumber9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber9.setText("9");
        jButtonNumber9.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber9ActionPerformed(evt);
            }
        });

        jButtonNumber0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNumber0.setText("0");
        jButtonNumber0.setPreferredSize(new java.awt.Dimension(0, 30));
        jButtonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber0ActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSub.setText("-");
        jButtonSub.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        jButtonMul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMul.setText("×");
        jButtonMul.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulActionPerformed(evt);
            }
        });

        jButtonDivi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDivi.setText("÷");
        jButtonDivi.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiviActionPerformed(evt);
            }
        });

        jButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setText("0");

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReset.setText("C");
        jButtonReset.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonClear.setText("CE");
        jButtonClear.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDecimal.setText(".");
        jButtonDecimal.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecimalActionPerformed(evt);
            }
        });

        jButtonNegative.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNegative.setText("+/-");
        jButtonNegative.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativeActionPerformed(evt);
            }
        });

        jButtonDividedByX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDividedByX.setText("1/x");
        jButtonDividedByX.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonDividedByX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividedByXActionPerformed(evt);
            }
        });

        jButtonPercent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPercent.setText("%");
        jButtonPercent.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPercentActionPerformed(evt);
            }
        });

        jButtonSqrtRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSqrtRoot.setText("√");
        jButtonSqrtRoot.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonSqrtRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrtRootActionPerformed(evt);
            }
        });

        jButtonBackspace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBackspace.setText("←");
        jButtonBackspace.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });

        jButtonMemoryClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMemoryClear.setText("MC");
        jButtonMemoryClear.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryClearActionPerformed(evt);
            }
        });

        jButtonMemoryRead.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMemoryRead.setText("MR");
        jButtonMemoryRead.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMemoryRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryReadActionPerformed(evt);
            }
        });

        jButtonMemorySave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMemorySave.setText("MS");
        jButtonMemorySave.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMemorySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemorySaveActionPerformed(evt);
            }
        });

        jButtonMemoryAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMemoryAdd.setText("M+");
        jButtonMemoryAdd.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMemoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryAddActionPerformed(evt);
            }
        });

        jButtonMemorySub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMemorySub.setText("M-");
        jButtonMemorySub.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonMemorySub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemorySubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDisplay)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBackspace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(jButtonMemoryClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNumber7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNumber4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNumber1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonNumber8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(jButtonMemoryRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNumber5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButtonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonNumber3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(jButtonMemorySave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonNumber9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonNumber6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonMul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addComponent(jButtonMemoryAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNegative, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDivi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jButtonMemorySub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSqrtRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDividedByX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMemoryClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButtonMemoryRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMemorySave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMemoryAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMemorySub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNegative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSqrtRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNumber6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButtonMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDividedByX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNumber5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNumber4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonNumber1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jButtonNumber2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNumber3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber0ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber0);
    }//GEN-LAST:event_jButtonNumber0ActionPerformed

    private void jButtonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber1ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber1);
    }//GEN-LAST:event_jButtonNumber1ActionPerformed

    private void jButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber2ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber2);
    }//GEN-LAST:event_jButtonNumber2ActionPerformed

    private void jButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber3ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber3);
    }//GEN-LAST:event_jButtonNumber3ActionPerformed

    private void jButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber4ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber4);
    }//GEN-LAST:event_jButtonNumber4ActionPerformed

    private void jButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber5ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber5);
    }//GEN-LAST:event_jButtonNumber5ActionPerformed

    private void jButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber6ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber6);
    }//GEN-LAST:event_jButtonNumber6ActionPerformed

    private void jButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber7ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber7);
    }//GEN-LAST:event_jButtonNumber7ActionPerformed

    private void jButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber8ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber8);
    }//GEN-LAST:event_jButtonNumber8ActionPerformed

    private void jButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber9ActionPerformed
        // TODO add your handling code here:
        addText(jButtonNumber9);
    }//GEN-LAST:event_jButtonNumber9ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldDisplay.setText("0");
        firstNum = 0;
        secondNum = 0;
        total = 0;
        operator = 0;
        zeroDisp = false;
        decDisp = false;
        acPress = true;
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            operator = 1;
            numberAdd = false;
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            operator = 2;
            numberAdd = false;
        }
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMulActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            operator = 3;
            numberAdd = false;
        }
    }//GEN-LAST:event_jButtonMulActionPerformed

    private void jButtonDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiviActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            operator = 4;
            numberAdd = false;
        }
    }//GEN-LAST:event_jButtonDiviActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            try {
                secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));

                if (operator == 0) {
                    total = secondNum;
                    setText();
                }
                if (operator == 1) {
                    total = logic.add(firstNum, secondNum);
                    setText();
                } else if (operator == 2) {
                    total = logic.substract(firstNum, secondNum);
                    setText();
                } else if (operator == 3) {
                    total = logic.multiply(firstNum, secondNum);
                    setText();
                } else if (operator == 4) {
                    total = logic.divide(firstNum, secondNum);
                    setText();
                } else if (operator == 5) {
                    total = logic.percent(firstNum, secondNum);
                    setText();
                }
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
            firstNum = 0;
            secondNum = 0;
            operator = 0;
            total = 0;
            zeroDisp = false;
            decDisp = false;
        }
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            jTextFieldDisplay.setText("0");
            zeroDisp = false;
            decDisp = false;
        }
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativeActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            try {
                secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                total = logic.negateOfX(secondNum);
                setText();
                zeroDisp = false;
                decDisp = false;
                total = 0;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonNegativeActionPerformed

    private void jButtonDividedByXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividedByXActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            try {
                secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                if (secondNum == 0) {
                    throw new Exception("Syntax Error");
                }
                total = logic.oneDivideByX(secondNum);
                setText();
                zeroDisp = false;
                decDisp = false;
                total = 0;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonDividedByXActionPerformed

    private void jButtonPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPercentActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            try {
                secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                total = logic.percent(firstNum, secondNum);
                setText();
                zeroDisp = false;
                decDisp = false;
                total = 0;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonPercentActionPerformed

    private void jButtonSqrtRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrtRootActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            prevTotal();
            try {
                secondNum = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                if (secondNum < 0) {
                    throw new Exception();
                }
                total = logic.sqrRoot(secondNum);
                setText();
                zeroDisp = false;
                decDisp = false;
                total = 0;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonSqrtRootActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            int length;
            String str = jTextFieldDisplay.getText();
            length = str.length();
            if (length > 1) {
                str = str.substring(0, length - 1);
                jTextFieldDisplay.setText(str);
            } else if (length == 1) {
                jTextFieldDisplay.setText("0");
                zeroDisp = false;
                decDisp = false;
            }
        }
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void jButtonMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryClearActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            jTextFieldDisplay.setText(String.valueOf(memory));
            memory = 0;
            zeroDisp = false;
            decDisp = false;
        }
    }//GEN-LAST:event_jButtonMemoryClearActionPerformed

    private void jButtonMemoryReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryReadActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            jTextFieldDisplay.setText(String.valueOf(memory));
            zeroDisp = false;
            decDisp = false;
        }
    }//GEN-LAST:event_jButtonMemoryReadActionPerformed

    private void jButtonMemorySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemorySaveActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            try {
                memory = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                jTextFieldDisplay.setText(String.valueOf(memory));
                zeroDisp = false;
                decDisp = false;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonMemorySaveActionPerformed

    private void jButtonMemoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryAddActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            try {
                memory = memory + Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                zeroDisp = false;
                decDisp = false;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonMemoryAddActionPerformed

    private void jButtonMemorySubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemorySubActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            try {
                memory = memory + Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
                zeroDisp = false;
                decDisp = false;
            } catch (Exception e) {
                jTextFieldDisplay.setText("Syntax Error");
                acPress = false;
            }
        }
    }//GEN-LAST:event_jButtonMemorySubActionPerformed

    private void jButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecimalActionPerformed
        // TODO add your handling code here:
        if (acPress) {
            if (!decDisp) {
                jTextFieldDisplay.setText(jTextFieldDisplay.getText() + ".");
                decDisp = true;
            } else {
                jTextFieldDisplay.setText("Error");
                zeroDisp = false;
                decDisp = false;
            }
        }
    }//GEN-LAST:event_jButtonDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDecimal;
    private javax.swing.JButton jButtonDivi;
    private javax.swing.JButton jButtonDividedByX;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMemoryAdd;
    private javax.swing.JButton jButtonMemoryClear;
    private javax.swing.JButton jButtonMemoryRead;
    private javax.swing.JButton jButtonMemorySave;
    private javax.swing.JButton jButtonMemorySub;
    private javax.swing.JButton jButtonMul;
    private javax.swing.JButton jButtonNegative;
    private javax.swing.JButton jButtonNumber0;
    private javax.swing.JButton jButtonNumber1;
    private javax.swing.JButton jButtonNumber2;
    private javax.swing.JButton jButtonNumber3;
    private javax.swing.JButton jButtonNumber4;
    private javax.swing.JButton jButtonNumber5;
    private javax.swing.JButton jButtonNumber6;
    private javax.swing.JButton jButtonNumber7;
    private javax.swing.JButton jButtonNumber8;
    private javax.swing.JButton jButtonNumber9;
    private javax.swing.JButton jButtonPercent;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSqrtRoot;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
