// ======= DO NOT EDIT THIS FILE ============
public class Car
 {String owner;
  int rate,price;
  Car(String xOwner, int xRate, int xPrice)
   {owner=xOwner;rate=xRate;price=xPrice;
   }
  public String toString()
   {return("(" +owner+","+rate + "," + price + ")");
   }
 }
